<?php

namespace EspaceParentBundle\Repository;

/**
 * childRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class childRepository extends \Doctrine\ORM\EntityRepository
{

}
