<?php

namespace EspaceParentBundle\Repository;

/**
 * complaintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class complaintRepository extends \Doctrine\ORM\EntityRepository
{
}
