<?php

namespace EspaceParentBundle\Repository;

/**
 * viewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class viewRepository extends \Doctrine\ORM\EntityRepository
{
}
