class_homepage:
    path:     /kindoclasses
    defaults: { _controller: ClassBundle:Default:indexClass}

class_class:
    resource: "@ClassBundle/Resources/config/routing/classe.yml"
    prefix:   /class

