#first:
  #  resource: "@FirstBundle/Resources/config/routing.yml"
    #prefix:   /

app:
    resource: '@AppBundle/routing.yml'
    prefix:   /

activity:
    resource: "@ActivityBundle/Resources/config/routing.yml"
    prefix:   /activity

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /event




# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


transport:
    resource: "@TransportBundle/Resources/config/routing.yml"
    prefix:   /

activity_timetable:
    resource: "@ActivityBundle/Resources/config/routing/timetable.yml"
    prefix:   /timetable


my_homepage:
    path:     /
    defaults: { _controller: ActivityBundle:Default:indexAct}

activity_page:
    path:     /act
    defaults: { _controller: ActivityBundle:Default:indexAct}
    methods: GET

class:
    resource: "@ClassBundle/Resources/config/routing.yml"
    prefix:   /



toiba_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yaml"


menu_indexF:
    path:       /indexF
    defaults:   {_controller: RestoNurseryBundle:Menu:indexF}

menu_indexB:
    path:       /indexB
    defaults:   {_controller: RestoNurseryBundle:Default:indexB}

restonursery_restonursery:
    resource: "@RestoNurseryBundle/Resources/config/myrouting.yml"

espace_parent:
    resource: "@EspaceParentBundle/Resources/config/routing.yml"
    prefix:   /
espace_parent_view:
    resource: "@EspaceParentBundle/Controller/viewController.php"
    type:     annotation

espace_parent_complaint:
    resource: "@EspaceParentBundle/Controller/complaintController.php"
    type:     annotation

espace_parent_child:
    resource: "@EspaceParentBundle/Controller/childController.php"
    type:     annotation
espace_child:
    resource: "@EspaceParentBundle/Resources/config/routing.yml"
    prefix:   /


