activity:
    resource: "@ActivityBundle/Resources/config/routing.yml"
    prefix:   /activity

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /event



app:
    resource: '@AppBundle/routing.yml'

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

first:
    resource: "@FirstBundle/Resources/config/routing.yml"
    prefix:   /

transport:
    resource: "@TransportBundle/Resources/config/routing.yml"
    prefix:   /

activity_timetable:
    resource: "@ActivityBundle/Resources/config/routing/timetable.yml"
    prefix:   /timetable


my_homepage:
    path:     /
    defaults: { _controller: ActivityBundle:Default:indexAct}

activity_page:
    path:     /act
    defaults: { _controller: ActivityBundle:Default:indexAct}
    methods: GET

class:
    resource: "@ClassBundle/Resources/config/routing.yml"
    prefix:   /



toiba_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yaml"