homepage:
  path:     /
  defaults: { _controller: AppBundle:Default:index }
select_type_menu:
  path:     /selecttype
  defaults: { _controller: AppBundle:Default:showselect }
confirm_type_account:
  path:     /confirmtype
  defaults: { _controller: AppBundle:Default:confirmtype }