<?php

namespace TransportBundle\Repository;

/**
 * TraffectationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraffectationRepository extends \Doctrine\ORM\EntityRepository
{
}
